### ISSUE TITLE
'Connection refused' error when trying to use a sample code

### ISSUE THREAD

**Issue by jeka-mel** [zwopple/PocketSocket#19]
Hello,

I recently was trying to use your code to test client server WebSockets communications on iOS. I've just grabbed a client & server code from you sample and no matter which values I used, I was getting this error when was trying to connect to your WebSocket server using your WebSocket client:

The websocket handshake/connection failed with an error: Error Domain=NSPOSIXErrorDomain Code=61 "The operation couldn’t be completed. Connection refused"

Thanks!

**Comment by mrjjwright** [comment]
Same with me.

**Comment by coveloper** [comment]
+1

**Comment by arsinio** [comment]
I was able to resolve this issue by making the modifications indicated in #34

**Comment by slreddy1137** [comment]
Hi Team,

I have made changes suggested in #34 but still it doesn't work, can anyone please help me on this.

**Comment by robertjpayne** [comment]
@slreddy1137 any chance you can share a bit of the code you are using to connect?

**Comment by slreddy1137** [comment]
Hi Robert,

Thanks Robert for reverting back on this.

i am able to connect now, it works, i m looking to putting TLS, i have opened another thread, can you please help me here

https://github.com/zwopple/PocketSocket/issues/41


I am able to make it as web server and client on the app, now need to have TLS between these two, i have one valid certificate, but how to pass it from webSocketClient while initiating connection and how can webSocketServer validates it, can you help on this please.

Thanks in advance.

**Comment by slreddy1137** [comment]
@robertjpayne , can you please help me with the TLS connection, i have a valid .cer certificate, but unable to send it, can you help on this please.


https://github.com/zwopple/PocketSocket/issues/41

**Comment by rajuiosdeveloper** [comment]
The websocket handshake/connection failed with an error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"
