### ISSUE TITLE
EXC_BAD_ACCESS in PSWebSocketNetworkThread

### ISSUE THREAD

**Issue by nickgravelyn** [zwopple/PocketSocket#21]
I'm having this issue pop up when using PocketSocket, but it's not 100% reproducible. Seems to be somehow timing related. For context, I'm using the library to help unit test a web socket consumer library, so we start/stop the web socket server before/after each test. This error doesn't always happen, but seems to happen enough that it's causing us some issues.

![screen shot 2014-12-17 at 10 21 03 am](https://cloud.githubusercontent.com/assets/361789/5476411/7fe24eee-85d6-11e4-80f1-7a8d341e7318.PNG)

Let me know if there's more information I can give you to help in tracking this down.

**Comment by robertjpayne** [comment]
Going to close this for now, believe it has been fixed in develop.
