### ISSUE TITLE
Output throttling (notification when space available to send)

### ISSUE THREAD

**Issue by snej** [zwopple/PocketSocket#32]
A client might have a lot of messages to send, but doesn't want to push them to the WebSocket faster than they can be delivered. For example, it might want to send a while directory of files as individual messages, but if it just does it naively it'll end up reading all the files into messages and filling up memory before the socket can send them.

This can be handled by a delegate callback that tells the client that all pending messages have been sent and there's room for more. Then the client can post messages in batches. I've added this to a different WebSocket implementation and it worked well.

**Comment by robertjpayne** [comment]
In develop have now added a `paused` on both input and output. There is also two optional delegates about when the input/output have been flushed.
