### ISSUE TITLE
VOIP Background Mode

### ISSUE THREAD

**Issue by roberte3** [zwopple/PocketSocket#36]
I'd like to add support for VOIP backgrounding to enable long polling websockets for an app I've taken over support on.  (Beyond the 10minute app background mode). 

I know that with socketRocket I can change the NSStreamNetworkServiceType to VOIP and enable this support. Any thoughts on how to enable this in PocketSocket?

**Comment by robertjpayne** [comment]
@roberte3 you shouldn't really do this, the VOIP mode should only be used for VOIP applications and requires a special entitlement from Apple.
