### ISSUE TITLE
How to add Subprotocol to a socket Connection

### ISSUE THREAD

**Issue by Raj123456788** [zwopple/PocketSocket#43]
I need to add subprotocol to the following code but I don't see a way to do it. is there a way I can add sub protocol to my socket connection?

`#import <PSWebSocket/PSWebSocket.h>

@interface AppDelegate() <PSWebSocketDelegate>

@property (nonatomic, strong) PSWebSocket *socket;

@end
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.backgroundColor = [UIColor whiteColor];
    [self.window makeKeyAndVisible];

    // create the NSURLRequest that will be sent as the handshake
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"wss://example.com"]];

    // create the socket and assign delegate
    self.socket = [PSWebSocket clientSocketWithRequest:request];
    self.socket.delegate = self;

    // open socket
    [self.socket open];

    return YES;
}
`

**Comment by robertjpayne** [comment]
@Raj123456788 make a `NSMutableURLRequest` and add a `Sec-Websocket-Protocol` header with your desired protocol before passing it into the `PSWebSocket`.

There is no validation on web socket protocols, as it is the server's responsibility to reject the connection if it cannot handle the specified protocol.
